import { ProductListProps } from "./ProductList";

export const MockProductListProps: ProductListProps = {
  products: [
    {
      gender: "mens",
      category: "boots",
      style: "captain",
      price: 199,
      slug: "mens-boots-captain-matteblack",
      color: "matte black",
      images: [
        "/images/mensproducts/captain/matteblack-1.webp",
        "/images/mensproducts/captain/matteblack-2.webp",
        "/images/mensproducts/captain/matteblack-3.webp",
        "/images/mensproducts/captain/matteblack-4.webp",
        "/images/mensproducts/captain/matteblack-5.webp",
        "/images/mensproducts/captain/matteblack-6.webp",
      ],
      sizes: [
        { size: "6", stock: 100 },
        { size: "7", stock: 100 },
        { size: "8", stock: 100 },
        { size: "9", stock: 100 },
        { size: "10", stock: 100 },
        { size: "11", stock: 100 },
        { size: "12", stock: 100 },
        { size: "13", stock: 100 },
        { size: "14", stock: 100 },
      ],
      featureImage: "/images/mensproducts/captain/matteblack-about.webp",
      productFeatures: [
        "Black Matte Rugged & Resilient Leather",
        "Goodyear Welt Construction for Longevity",
        "Fully Lined Supple Glove Leather Interior",
        "Hardwearing Steel Shanks",
        "Poron® Antimicrobial Shock Absorbing Insoles",
        "Long-Lasting Kevlar® Blend Laces",
        "Custom Developed Reinforced Eyelets",
        "Cork-Bed Midsoles that Form to Your Feet",
        "Durable Studded Rubber Outsoles",
        "Handcrafted with Integrity",
      ],
      description:
        "Built for the men who wear their boots hard. The Rugged & Resilient matte leather upper, sourced exclusively from Tier 1 USA cattle hides, was custom created to look great with years of hard wear and minimal care. From the Kevlar® blend laces to the durable steel shank, every material was carefully created so that you can go the extra mile with confidence.",
    },
    {
      gender: "mens",
      category: "boots",
      style: "captain",
      price: 199,
      slug: "mens-boots-captain-blue",
      color: "blue",
      images: [
        "/images/mensproducts/captain/blue-1.webp",
        "/images/mensproducts/captain/blue-2.webp",
        "/images/mensproducts/captain/blue-3.webp",
        "/images/mensproducts/captain/blue-4.webp",
        "/images/mensproducts/captain/blue-5.webp",
        "/images/mensproducts/captain/blue-6.webp",
      ],
      sizes: [
        { size: "6", stock: 100 },
        { size: "7", stock: 100 },
        { size: "8", stock: 100 },
        { size: "9", stock: 100 },
        { size: "10", stock: 100 },
        { size: "11", stock: 100 },
        { size: "12", stock: 100 },
        { size: "13", stock: 100 },
        { size: "14", stock: 100 },
      ],
      featureImage: "/images/mensproducts/captain/blue-about.webp",
      productFeatures: [
        "Marino Matte Rugged & Resilient Leather",
        "Goodyear Welt Construction for Longevity",
        "Fully Lined Supple Glove Leather Interior",
        "Hardwearing Steel Shanks",
        "Poron® Antimicrobial Shock Absorbing Insoles",
        "Long-Lasting Kevlar® Blend Laces",
        "Custom Developed Reinforced Eyelets",
        "Cork-Bed Midsoles that Form to Your Feet",
        "Durable Studded Rubber Outsoles",
        "Handcrafted with Integrity",
      ],
      description:
        "Built for the men who wear their boots hard. The Rugged & Resilient matte leather upper, sourced exclusively from Tier 1 USA cattle hides, was custom created to look great with years of hard wear and minimal care. From the Kevlar® blend laces to the durable steel shank, every material was carefully created so that you can go the extra mile with confidence.",
    },
    {
      gender: "mens",
      category: "boots",
      style: "captain",
      price: 199,
      slug: "mens-boots-captain-canyon",
      color: "canyon",
      images: [
        "/images/mensproducts/captain/canyon-1.webp",
        "/images/mensproducts/captain/canyon-2.webp",
        "/images/mensproducts/captain/canyon-3.webp",
        "/images/mensproducts/captain/canyon-4.webp",
        "/images/mensproducts/captain/canyon-5.webp",
        "/images/mensproducts/captain/canyon-6.webp",
      ],
      sizes: [
        { size: "6", stock: 100 },
        { size: "7", stock: 100 },
        { size: "8", stock: 100 },
        { size: "9", stock: 100 },
        { size: "10", stock: 100 },
        { size: "11", stock: 100 },
        { size: "12", stock: 100 },
        { size: "13", stock: 100 },
        { size: "14", stock: 100 },
      ],
      featureImage: "/images/mensproducts/captain/canyon-about.webp",
      productFeatures: [
        "Canyon Rugged & Resilient Leather",
        "Goodyear Welt Construction for Longevity",
        "Fully Lined Supple Glove Leather Interior",
        "Hardwearing Steel Shanks",
        "Poron® Antimicrobial Shock Absorbing Insoles",
        "Long-Lasting Kevlar® Blend Laces",
        "Custom Developed Reinforced Eyelets",
        "Cork-Bed Midsoles that Form to Your Feet",
        "Durable Studded Rubber Outsoles",
        "Handcrafted with Integrity",
      ],
      description:
        "Built for the men who wear their boots hard. The Rugged & Resilient matte leather upper, sourced exclusively from Tier 1 USA cattle hides, was custom created to look great with years of hard wear and minimal care. From the Kevlar® blend laces to the durable steel shank, every material was carefully created so that you can go the extra mile with confidence.",
    },
    {
      gender: "mens",
      category: "boots",
      style: "captain",
      price: 199,
      slug: "mens-boots-captain-grey",
      color: "grey",
      images: [
        "/images/mensproducts/captain/grey-1.webp",
        "/images/mensproducts/captain/grey-2.webp",
        "/images/mensproducts/captain/grey-3.webp",
        "/images/mensproducts/captain/grey-4.webp",
        "/images/mensproducts/captain/grey-5.webp",
        "/images/mensproducts/captain/grey-6.webp",
      ],
      sizes: [
        { size: "6", stock: 100 },
        { size: "7", stock: 100 },
        { size: "8", stock: 100 },
        { size: "9", stock: 100 },
        { size: "10", stock: 100 },
        { size: "11", stock: 100 },
        { size: "12", stock: 100 },
        { size: "13", stock: 100 },
        { size: "14", stock: 100 },
      ],
      featureImage: "/images/mensproducts/captain/grey-about.webp",
      productFeatures: [
        "Grey Matte Rugged & Resilient Leather",
        "Goodyear Welt Construction for Longevity",
        "Fully Lined Supple Glove Leather Interior",
        "Hardwearing Steel Shanks",
        "Poron® Antimicrobial Shock Absorbing Insoles",
        "Long-Lasting Kevlar® Blend Laces",
        "Custom Developed Reinforced Eyelets",
        "Cork-Bed Midsoles that Form to Your Feet",
        "Durable Studded Rubber Outsoles",
        "Handcrafted with Integrity",
      ],
      description:
        "Built for the men who wear their boots hard. The Rugged & Resilient matte leather upper, sourced exclusively from Tier 1 USA cattle hides, was custom created to look great with years of hard wear and minimal care. From the Kevlar® blend laces to the durable steel shank, every material was carefully created so that you can go the extra mile with confidence.",
    },
    {
      gender: "mens",
      category: "boots",
      style: "captain",
      price: 199,
      slug: "mens-boots-captain-tobacco",
      color: "tobacco",
      images: [
        "/images/mensproducts/captain/tobacco-1.webp",
        "/images/mensproducts/captain/tobacco-2.webp",
        "/images/mensproducts/captain/tobacco-3.webp",
        "/images/mensproducts/captain/tobacco-4.webp",
        "/images/mensproducts/captain/tobacco-5.webp",
        "/images/mensproducts/captain/tobacco-6.webp",
      ],
      sizes: [
        { size: "6", stock: 100 },
        { size: "7", stock: 100 },
        { size: "8", stock: 100 },
        { size: "9", stock: 100 },
        { size: "10", stock: 100 },
        { size: "11", stock: 100 },
        { size: "12", stock: 100 },
        { size: "13", stock: 100 },
        { size: "14", stock: 100 },
      ],
      featureImage: "/images/mensproducts/captain/tobacco-about.webp",
      productFeatures: [
        "Tobacco Rugged & Resilient Leather",
        "Goodyear Welt Construction for Longevity",
        "Fully Lined Supple Glove Leather Interior",
        "Hardwearing Steel Shanks",
        "Poron® Antimicrobial Shock Absorbing Insoles",
        "Long-Lasting Kevlar® Blend Laces",
        "Custom Developed Reinforced Eyelets",
        "Cork-Bed Midsoles that Form to Your Feet",
        "Durable Studded Rubber Outsoles",
        "Handcrafted with Integrity",
      ],
      description:
        "Built for the men who wear their boots hard. The Rugged & Resilient matte leather upper, sourced exclusively from Tier 1 USA cattle hides, was custom created to look great with years of hard wear and minimal care. From the Kevlar® blend laces to the durable steel shank, every material was carefully created so that you can go the extra mile with confidence.",
    },
  ],
  style: "captain",
};
