import type { NextPage } from "next";
import Head from "next/head";
import Featured from "../components/Featured/Featured";
import FeaturedCollection from "../components/FeaturedCollection/FeaturedCollection";
import Footer from "../components/Footer/Footer";
import Prefooter from "../components/Prefooter/Prefooter";
import Slideshow from "../components/Slideshow/Slideshow";
import Testimonials from "../components/Testimonials/Testimonials";
import s from "../styles/pages/home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={s.home}>
      <Head>
        <title>Thursday | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Slideshow */}
      <Slideshow />

      {/* Testimonials */}
      <Testimonials />

      {/* Featured */}
      <Featured />

      {/* Featured Collection */}
      <FeaturedCollection />

      {/* Prefooter */}
      <Prefooter />

      {/* Footer */}
      <Footer />
    </div>
  );
};

export default Home;
